# Generated by Django 5.0.1 on 2024-01-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('medicine_form', models.CharField(choices=[('tablet', '정제'), ('capsule', '캡슐'), ('liquid', '액제'), ('other', '기타')], default='other', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notify_time', models.CharField(choices=[('morning', '아침'), ('lunch', '점심'), ('dinner', '저녁')], default='morning', max_length=200)),
            ],
        ),
    ]
