# Generated by Django 5.0.1 on 2024-01-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_remove_medicine_medicine_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dinner_dose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='lunch_dose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='morning_dose',
            field=models.BooleanField(default=False),
        ),
    ]
