# Generated by Django 5.0.1 on 2024-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_medicine_dinner_dose_medicine_lunch_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dinner_dose_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='lunch_dose_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='morning_dose_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
