# Generated by Django 5.0.1 on 2024-01-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_medicine_dinner_dose_time_medicine_lunch_dose_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
