# Generated by Django 5.0.1 on 2024-01-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0006_medicine_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_time', models.CharField(choices=[('morning', '아침'), ('lunch', '점심'), ('dinner', '저녁')], max_length=10)),
                ('dose_taken', models.BooleanField(default=False)),
                ('dose_taken_time', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='manage.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'dose_time')},
            },
        ),
    ]
