# Generated by Django 5.0.1 on 2024-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('notice', '공지사항'), ('free', '자유게시판'), ('question', '질문게시판'), ('review', '후기게시판'), ('suggestion', '건의사항 게시판')], default='free', max_length=20),
        ),
    ]
