# Generated by Django 5.0.1 on 2024-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('공지사항', '공지사항'), ('자유게시판', '자유게시판'), ('질문게시판', '질문게시판'), ('후기게시판', '후기게시판'), ('건의사항', '건의사항')], default='free', max_length=20),
        ),
    ]
